// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanControl.Backend.Data;

#nullable disable

namespace UrbanControl.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325065216_AddSistemaPermisosSofisticado")]
    partial class AddSistemaPermisosSofisticado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanControl.Backend.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manzana")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SuperficieM2")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioBaseM2")
                        .HasColumnType("numeric");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoReserva")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LoteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.CapacidadSubmodulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SubmoduloId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoPermisoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoPermisoId");

                    b.HasIndex("SubmoduloId", "TipoPermisoId")
                        .IsUnique();

                    b.ToTable("CapacidadSubmodulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubmoduloId = 1,
                            TipoPermisoId = 1
                        },
                        new
                        {
                            Id = 2,
                            SubmoduloId = 1,
                            TipoPermisoId = 2
                        },
                        new
                        {
                            Id = 3,
                            SubmoduloId = 1,
                            TipoPermisoId = 3
                        },
                        new
                        {
                            Id = 4,
                            SubmoduloId = 2,
                            TipoPermisoId = 1
                        },
                        new
                        {
                            Id = 5,
                            SubmoduloId = 2,
                            TipoPermisoId = 2
                        },
                        new
                        {
                            Id = 6,
                            SubmoduloId = 2,
                            TipoPermisoId = 3
                        },
                        new
                        {
                            Id = 7,
                            SubmoduloId = 2,
                            TipoPermisoId = 4
                        },
                        new
                        {
                            Id = 8,
                            SubmoduloId = 3,
                            TipoPermisoId = 1
                        },
                        new
                        {
                            Id = 9,
                            SubmoduloId = 3,
                            TipoPermisoId = 2
                        },
                        new
                        {
                            Id = 10,
                            SubmoduloId = 3,
                            TipoPermisoId = 5
                        });
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icono = "pi pi-box",
                            Nombre = "Inventario",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Icono = "pi pi-shopping-cart",
                            Nombre = "Ventas",
                            Orden = 2
                        });
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.PermisoRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadSubmoduloId")
                        .HasColumnType("integer");

                    b.Property<bool>("Concedido")
                        .HasColumnType("boolean");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CapacidadSubmoduloId");

                    b.HasIndex("RolId", "CapacidadSubmoduloId")
                        .IsUnique();

                    b.ToTable("PermisosRoles");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso total",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Solo ventas y clientes",
                            Nombre = "Vendedor"
                        });
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.Submodulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ModuloId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RutaAngular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Submodulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuloId = 1,
                            Nombre = "Proyectos",
                            RutaAngular = "/proyectos"
                        },
                        new
                        {
                            Id = 2,
                            ModuloId = 1,
                            Nombre = "Lotes",
                            RutaAngular = "/lotes"
                        },
                        new
                        {
                            Id = 3,
                            ModuloId = 2,
                            Nombre = "Reservas",
                            RutaAngular = "/reservas"
                        });
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.TipoPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("TipoPermisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Ver",
                            Slug = "view"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Crear",
                            Slug = "create"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Editar",
                            Slug = "edit"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Eliminar",
                            Slug = "delete"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Imprimir PDF",
                            Slug = "pdf"
                        });
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.Lote", b =>
                {
                    b.HasOne("UrbanControl.Backend.Models.Proyecto", "Proyecto")
                        .WithMany("Lotes")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.Reserva", b =>
                {
                    b.HasOne("UrbanControl.Backend.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanControl.Backend.Models.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanControl.Backend.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Lote");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.CapacidadSubmodulo", b =>
                {
                    b.HasOne("UrbanControl.Backend.Models.access_privilegios.Submodulo", "Submodulo")
                        .WithMany("Capacidades")
                        .HasForeignKey("SubmoduloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanControl.Backend.Models.access_privilegios.TipoPermiso", "TipoPermiso")
                        .WithMany()
                        .HasForeignKey("TipoPermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submodulo");

                    b.Navigation("TipoPermiso");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.PermisoRol", b =>
                {
                    b.HasOne("UrbanControl.Backend.Models.access_privilegios.CapacidadSubmodulo", "Capacidad")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("CapacidadSubmoduloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UrbanControl.Backend.Models.access_privilegios.Rol", "Rol")
                        .WithMany("PermisosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacidad");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.Submodulo", b =>
                {
                    b.HasOne("UrbanControl.Backend.Models.access_privilegios.Modulo", "Modulo")
                        .WithMany("Submodulos")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.Proyecto", b =>
                {
                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.CapacidadSubmodulo", b =>
                {
                    b.Navigation("PermisosRoles");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.Modulo", b =>
                {
                    b.Navigation("Submodulos");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.Rol", b =>
                {
                    b.Navigation("PermisosRoles");
                });

            modelBuilder.Entity("UrbanControl.Backend.Models.access_privilegios.Submodulo", b =>
                {
                    b.Navigation("Capacidades");
                });
#pragma warning restore 612, 618
        }
    }
}
